name: grs
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.5.0
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^4.2.0
  new_version_plus: ^0.0.11
  intl_phone_field: ^3.2.0
  flutter_form_builder: ^9.1.1
  form_field_validator: ^1.1.0
  flutter_localization: ^0.1.14
  intl_translation: ^0.18.2
  intl_phone_number_field: ^0.1.8
  numeric_keyboard: ^1.1.0
  molten_navigationbar_flutter: ^1.0.1
  camera: ^0.10.5+5
  face_camera: ^0.0.8
  flutter_barcode_scanner: ^2.0.0
  google_maps_flutter: ^2.5.0
  flutter_config: ^2.0.2
  geolocator: ^10.1.0
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  device_info: ^2.0.3
  flutter_spinkit: ^5.2.0
  simple_annimated_staggered: ^0.0.3
  loading_overlay: ^0.3.0
  flutter_overlay_loader: ^2.0.0
  overlay_loading_progress: ^1.0.1
  loader_overlay: ^3.0.0
  cool_alert: ^2.0.1
  quickalert: ^1.0.2
  dio: ^5.3.3
  animated: ^2.0.0
  button_animations: ^2.0.0+3
  form_builder_validators: ^9.1.0
  custom_radio_grouped_button: ^2.2.1
  select_dialog: ^2.0.1
  speed_dial_fab: ^2.3.0
  awesome_select: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/resources/assets/images/
    - lib/resources/assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700