// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKqWtBhdqVTPkb7XF-3fze88uVMZyTHQ',
    appId: '1:248670712816:web:6eb55f8988be30049da335',
    messagingSenderId: '248670712816',
    projectId: 'grs-app-402508',
    authDomain: 'grs-app-402508.firebaseapp.com',
    databaseURL: 'https://grs-app-402508-default-rtdb.firebaseio.com',
    storageBucket: 'grs-app-402508.appspot.com',
    measurementId: 'G-YEVMP9L66Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-HjvsL8QgiKJAEC6zsi5aR5SXZom8d4',
    appId: '1:248670712816:android:af5dc3e003f24c049da335',
    messagingSenderId: '248670712816',
    projectId: 'grs-app-402508',
    databaseURL: 'https://grs-app-402508-default-rtdb.firebaseio.com',
    storageBucket: 'grs-app-402508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Id8pFhfn9g8vyq64QjYeWd5saFtFTp4',
    appId: '1:248670712816:ios:dcb372328d905e2b9da335',
    messagingSenderId: '248670712816',
    projectId: 'grs-app-402508',
    databaseURL: 'https://grs-app-402508-default-rtdb.firebaseio.com',
    storageBucket: 'grs-app-402508.appspot.com',
    iosBundleId: 'grs.afrizona.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Id8pFhfn9g8vyq64QjYeWd5saFtFTp4',
    appId: '1:248670712816:ios:202248bdf3591d0e9da335',
    messagingSenderId: '248670712816',
    projectId: 'grs-app-402508',
    databaseURL: 'https://grs-app-402508-default-rtdb.firebaseio.com',
    storageBucket: 'grs-app-402508.appspot.com',
    iosBundleId: 'grs.afrizona.com.RunnerTests',
  );
}
